openapi: 3.0.0
info:
  title: Kadaster - BRK-Bevragen API - Publiek rechtelijke beperkingen endpoints
  description: "De definitie van de Publiek rechtelijke beperkingen endpoints en components"
  version: "1.1.0"
paths:
  /publiekrechtelijkebeperkingen:
    get:
      operationId: GetPubliekrechtelijkeBeperkingen
      description: |
        Zoeken van de publiekrechtelijke beperkingen op een kadastraal onroerende zaak, adres of locatie.

        Met gebruik van de parameter expand kunnen gerelateerde stukdelen direct worden meegeladen.
      parameters:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/fields"
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/expand"
        - in: query
          name: kadastraalOnroerendeZaakIdentificatie
          description: "De unieke identificatie van een kadastraal onroerende zaak. Gezocht wordt naar publiekrechtelijke beperkingen die rusten op de onroerende zaak."
          schema:
            type: string
        - in: query
          name: nummeraanduidingIdentificatie
          description: "De unieke identificatie van een BAG nummeraanduiding. Gezocht wordt naar publiekrechtelijke beperkingen die rusten op dit adres."
          schema:
            type: string
        - in: query
          name: locatie
          description: Coordinaten van een locatie (punt) die gebruikt wordt om een object te zoeken. Let op, explode is false dus het formaat is ?locatie=194602.722,464154.308
          required: false
          explode: false
          schema:
            type: array
            minItems: 2
            maxItems: 2
            items:
              type: number
            example:
            - 196733.510
            - 439931.890
        - $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/contentCrs'
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/warning"
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/PubliekrechtelijkeBeperkingHalCollectie"
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/406"
        '412':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/412"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/415"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/500"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/503"
      tags:
      - Publiekrechtelijke Beperkingen
  /publiekrechtelijkebeperkingen/{publiekrechtelijkebeperkingidentificatie}:
    get:
      operationId: GetPubliekrechtelijkeBeperking
      description: |
        Raadplegen van een specifieke publiekrechtelijke beperking.

        Met gebruik van de parameter expand kunnen gerelateerde stukdelen direct worden meegeladen.
      parameters:
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/fields"
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/parameters/expand"
        - in: path
          name: publiekrechtelijkebeperkingidentificatie
          description: "De unieke identificatie van een publiekrechtelijke beperking"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/headers/warning"
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/PubliekrechtelijkeBeperkingHal"
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/403"
        '404':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/404"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/406"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/415"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/500"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/responses/503"
      tags:
      - Publiekrechtelijke Beperkingen
components:
  schemas:
    Werkingsgebied:
      type: "object"
      description: "Datgene waarop de beperking van toepassing is."
      properties:
        bgtObjectIdentificatie:
          description: "De unieke identificatie van een BGT object."
          type: "string"
        bagObject:
          $ref: "#/components/schemas/BagObject"
        kadastraalObjectIdentificatie:
          description: "De unieke identificatie van een kadastraal onroerende zaak."
          type: "array"
          items:
            type: "string"
        vrijeContour:
          $ref: "http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/polygonGeoJSON.yaml"
    BagObject:
      type: object
      properties:
        identificatie:
          type: string
          description: "Unieke identificatie van het BAG object"
        domein:
          $ref: "#/components/schemas/BagDomein_enum"
    BagDomein_enum:
      type: string
      description: "Aanduiding die aangeeft op welk type BAG-object de identificatie betrekking heeft"
      enum:
        - "NL.IMBAG.Woonplaats"
        - "NL.IMBAG.Openbareruimte"
        - "NL.IMBAG.Nummeraanduiding"
        - "NL.IMBAG.Verblijfsobject"
        - "NL.IMBAG.Pand"
    PubliekrechtelijkeBeperking:
      type: "object"
      description: "Beperkingen op een kadastraal onroerende zaak die door de overheid zijn opgelegd. Deze bepalen wat een eigenaar wel of niet mag doen met een woning, een ander gebouw of een stuk grond. Het gaat het bijvoorbeeld om beschermde monumenten, natuurmonumenten, bodembescherming, eisen die binnen de Woningwet worden gesteld, of maatregelen die nodig zijn voor landsverdediging."
      properties:
        identificatie:
          type: "string"
        domein:
          type: "string"
          description: "Het domein waartoe de identificatie behoort."
        grondslag:
          $ref: "domain.yaml#/components/schemas/Waardelijst"
          description: "Mogelijke waarden zijn te vinden in deze [Waardelijst](http://www.kadaster.nl/schemas/waardelijsten/AardAantekening/)"
        datumInWerking:
          type: "string"
          format: "date"
        datumBeeindiging:
          type: "string"
          format: "date"
        isGebaseerdOpStukdeelIdentificatie:
          type: "string"
          description: "De identificatie van het stukdeel (paragraaf in een akte met een rechtsfeit) waarop deze publiekrechtelijke beperking is gebaseerd."
        isVermeldInStukdeelIdentificaties:
          type: "array"
          description: "De identificaties van de stukdelen (paragrafen in een akte met een rechtsfeit) waarin deze publiekrechtelijke beperking gerechtigde is vermeld"
          items:
            type: "string"
        bevoegdGezag:
          $ref: "domain.yaml#/components/schemas/NietNatuurlijkPersoonBeperkt"
        werkingsgebied:
          $ref: "#/components/schemas/Werkingsgebied"
    PubliekrechtelijkeBeperkingHal:
      allOf:
      - $ref: "#/components/schemas/PubliekrechtelijkeBeperking"
      - properties:
          _links:
            $ref: "#/components/schemas/PubliekrechtelijkeBeperking_links"
          _embedded:
            $ref: "#/components/schemas/PubliekrechtelijkeBeperking_embedded"
    PubliekrechtelijkeBeperkingHalCollectie:
      type: "object"
      properties:
        _links:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalCollectionLinks"
        _embedded:
          type: "object"
          properties:
            publiekrechtelijkeBeperkingen:
              type: "array"
              items:
                $ref: "#/components/schemas/PubliekrechtelijkeBeperkingHal"
    PubliekrechtelijkeBeperking_embedded:
      type: "object"
      properties:
        isGebaseerdOpStukdeel:
            $ref: "stukken.yaml#/components/schemas/StukdeelHal"
        isVermeldInStukdelen:
          type: "array"
          items:
            $ref: "stukken.yaml#/components/schemas/StukdeelHal"
    PubliekrechtelijkeBeperking_links:
      type: "object"
      properties:
        self:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        isGebaseerdOpStukdeel:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        isVermeldInStukdelen:
          type: "array"
          items:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        bevoegdGezag:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.0.0/api-specificatie/common.yaml#/components/schemas/HalLink"
