name: Resolve OpenAPI specs

on:
  push:
    # paths:
    #   - specificatie/*.yaml
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: swagger-cli
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: validate specificatie/openapi.yaml
  resolve:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Swagger Codegen v3 yaml
        uses: ducksify/swagger-codegen-action@v3.0
        with:
          args: generate -i specificatie/openapi.yaml -l openapi-yaml -o specificatie/genereervariant
      - name: Swagger Codegen v3 json
        uses: ducksify/swagger-codegen-action@v3.0
        with:
          args: generate -i specificatie/openapi.yaml -l openapi -o specificatie/genereervariant
      - uses: actions/upload-artifact@master
        with:
          name: resolve artifacts
          path: specificatie/genereervariant/
  validateResolved:
    needs: resolve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: resolve artifacts
          path: specificatie/genereervariant
      - name: swagger-cli
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: validate specificatie/genereervariant/openapi.yaml
