name: Resolve OpenAPI specs

on:
  push:
    # paths:
    #   - specificatie/*.yaml
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: swagger-cli
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: validate specificatie/openapi.yaml
